sonar.projectKey=webuddhist_worker
sonar.organization=webuddhist
sonar.sources=worker_api
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Exclude model files, repository files, and generated code from code coverage
sonar.coverage.exclusions=**/*_models.py,**/*_response_models.py,**/*_repository.py,**/external_clients/**

# Exclude generated code from analysis entirely
sonar.exclusions=**/external_clients/**
